- .github/actions/docker/action.yml
- .github/workflows/ci-build.yml
> Fixoutputs

- .github/workflows/docker-bp.yml
This is a fix related to https://github.com/signalwire/freeswitch-docs/pull/2
> Adding swarm service as variable

- .github/actions/approval/action.yml
The approval-timeout isn't working anymore
> [Fix] Variable not working

- .github/actions/teleport/action.yml
> [fix] teleport action

- .github/workflows/iac.yml
Required for https://github.com/signalwire/cloud-product/issues/5260
> Add secrets required for OVH provisioning

- .github/workflows/cd-kubernetes-deploy.yml
- Pass the proxy URL as env, this change doesn't do anything for us, it just prevents secret leakage for public repos
> fix proxy variable

- .github/workflows/cd-swarm-deploy.yml
This PR transform the old endpoint ids that are already set as secret to an env variable
> fix endpoint_id

- .github/workflows/iac.yml
Solves https://github.com/signalwire/infrastructure-lives/actions/runs/4608456002/jobs/8144235801?pr=331
> setup terragrunt to run non-interactive due vault failures

- .github/actions/docker/action.yml
- .github/workflows/ci-build.yml
- .github/workflows/ci.yml
Follows Docker reference https://docs.docker.com/build/ci/github-actions/secrets/
> add support to docker secrets

- .github/workflows/ci-build.yml
- [#6664](https://github.com/signalwire/cloud-product/issues/6664)
Fix `BUILD_ARGS`
> attempt to fix build args

- .github/workflows/cd-swarm-deploy.yml
related to https://github.com/signalwire/conference-manager/actions/runs/4861751967/jobs/8672972796 
@ryanwi FYI 👆🏻
> remove break line causing escape problems

- .github/workflows/iac.yml
Required for https://github.com/signalwire/cloud-product/issues/5898
> Add OVH_CLOUD_PROJECT_SERVICE env to plan and apply steps

- .github/workflows/iac.yml
Required for https://github.com/signalwire/cloud-product/issues/5898
> Fix IAC validation environment

- .github/actions/notify-ci-result/action.yml
added `report` path input and taring the file in it.
> notify-ci-result actions bugfix/update

- .github/actions/notify-ci-result/action.yml
- [#7261](https://github.com/signalwire/cloud-product/issues/7261)
> updated notify-ci-result action's notification message

- .github/actions/docker/action.yml
Fix for https://github.com/docker/build-push-action/issues/910
> fix docker action

- .github/workflows/ci-build.yml
change build step id to docker_build to solve the conflict if the build directory exist in repo.
> change build step id to docker_build

- .github/workflows/ci-build.yml
> fix step name2

- .github/actions/test-ruby/action.yml
> Remove contribsys

- .github/actions/test-ruby/action.yml
- .github/workflows/ci-check.yml
- .github/workflows/ci.yml
Getting failures of missing env vars in some steps for a new repo being configured.
> Set .env earlier

- .github/actions/docker/action.yml
REF: https://docs.docker.com/build/ci/github-actions/secrets/
> add docker secrets flag

- .github/workflows/ci-rpm-packages.yml
New inputs: SIGNALWIRE_USERNAME,SIGNALWIRE_TOKEN and ADDITIONAL_PACKAGES.
> Add support for new inputs.

- .github/workflows/iac.yml
fix the comments on github pr + revert some changes related to Azure deploys
> revert changes

- .github/workflows/cd-swarm-deploy.yml
Seeing jobs fail due to it being required
> make it optional

- .github/actions/docker-compose/action.yml
Standardize on `docker compose` for consistency
> Switch to docker compose

- .github/actions/slack/action.yml
Reverts signalwire/actions-template#336
> Revert "Update slackapi/slack-github-action action to v2"

- .github/actions/update-gitops/action.yml
example use with
```
cd_prod:
name: "Deploy test"
runs-on: ubuntu-latest
steps:
- name: Deploy to staging test
uses: signalwire/actions-template/.github/actions/update-gitops@feat/swarm-gitops-rw
with:
GITOPS_REPOSITORY: ghorg/ghrepo
FILE_PATH: ./cdtest/cdtest.stack.yml
SERVICE_NAME: docs
IMAGE_TAG: registryorg/image:20250128-156-aa41844
CREATE_PR: false
ORCHESTRATOR: swarm
env:
GITOPS_PAT: ${{ secrets.GITOPS_PAT_STAGING }}
```
> Stack file updates thorugh GitOps

- .github/actions/docker/action.yml
Attempting to resolve issue caused by decommissioned GHA cache still being used.
https://github.com/orgs/community/discussions/160793
> Update to setup-buildx-action@v3

- .github/actions/rclone-s3-sync/action.yml
- .github/workflows/cicd-docker-build-and-distribute.yml
- Drop unused `meta-repo` Job
- Add `s3` artifact upload via `rclone`
> Add `s3` artifact upload via `rclone`
