signalwire/actions-template

.github/workflows/iac.yml

It solves the deprecation warnings that we see while connecting to the remote backend for state files.

Fix GitHub node12 deprecation by updating it to node 16

---

.github/actions/swarm-deploy/action.yml

This fixes `swarm-deploy` action. Taken from [signalwire/cantina-cloud/.github/actions/swarm-deploy](https://github.com/signalwire/cantina-cloud/blob/main/.github/actions/swarm-deploy/action.yml).

fixed swarm-deploy action

---

.github/actions/docker/action.yml
.github/actions/test-ruby/action.yml
.github/workflows/ci-check.yml

Docker buildx can't export manifest in case of multi-platform builds e.g. 
https://github.com/signalwire/devops-base-images/actions/runs/4107251005/jobs/7086492483#step:10:442
This commit bypass this step in our workflows

disable load in case of multi-platform build

---

.github/actions/helm-local/action.yml
.github/workflows/cd-kubernetes-deploy.yml

Implements the ```--set``` flag for Helm. 
Fulfills the need raised by https://github.com/signalwire/charts/pull/11

update cd k8s + helm action local to support inline values

---

.github/workflows/iac.yml

solves cross-project communication such as (https://github.com/signalwire/infrastructure-lives/actions/runs/4758011637/jobs/8455522130)

add non-interactive flag

---

.github/actions/test-dotnet/action.yml

I think we can skip the `mv .env.ci to .env` with the provided actions ability to load custom path?
This action seems a bit more reliable?

dotenv update

---

.github/actions/test-dotnet/action.yml

https://github.com/xom9ikk/dotenv
```
Run xom9ikk/dotenv@v2
with:
path: .env.ci
env:
DOTNET_ROOT: /usr/share/dotnet
Error: ENOTDIR: not a directory, open '.env.ci/.env'
```

Path is only for directory

---

.github/actions/test-dotnet/action.yml

This step appears to be failing consistently across repos. The GHA runs, overall, are still succeeded, but this failure shows in the results as a failure.

Remove failing step

---

.github/workflows/ci-build.yml

- [7480](https://github.com/signalwire/cloud-product/issues/7480)
`actions/checkout@v3` has a [bug](https://github.com/actions/checkout/issues/1359), which is cloning `master` branch while trigger event for workflow is `pull_request`. This PR fixed it by passing `ref: ${{ github.event.pull_request.head.ref || github.ref }}` to checkout steps.

fix checkout for ci-build

---

.github/actions/notify-ci-result/action.yml

After discussing with Andrey, artifacts need to be retained longer than the five days that were specified in the notify-ci-result action. This PR removes the `retention-period` setting, which should result in retention defaulting to the org setting.

Remove retention period for artifacts in notify-ci-result

---

.github/workflows/ci-build.yml

added a Optional `REF` input to `ci-build` workflow in order to make it possible for the caller to specify which ref (branch/commit/tag) to checkout and build.

added REF to inputs in ci-build

---

.github/actions/test-ruby/action.yml

Ruby 2.7 was EOL as of earlier this year.

Update default Ruby

---

.github/actions/docker/action.yml
.github/workflows/ci-build.yml

Support to https://github.com/signalwire/cloud-product/issues/8219

configure docker caching

---

.github/workflows/ci-deb-packages-v2.yml

1. Rework DEB build script:
- add more verbosity
- add basic error handling
- use GITHUB_RUN_ID in script path
2. Extend custom variables with image tag based on distro codename and arch.
3. Set unique name for `actions/upload` steps to avoid `(409) Conflict: an artifact with this name already exists on the workflow run`

Rework DEB build script and actions/upload steps.

---

.github/workflows/cd-libs-metadata.yml
.github/workflows/ci-deb-packages-v2.yml
.github/workflows/ci-libs-metadata-v2.yml

* Add DISTRO_CODENAME support.
* Exit early in 'Sync changes' when no diff.

Package handling changes.

---

.github/workflows/cd-libs-metadata.yml

Rework handling of `Sync changes` in case when there are no changes to commit and remove redundant git branch checkouts.
Related to GHA packaging.

GHA packaging: Rework Sync changes.

---

.github/workflows/iac.yml

action is broken after upgrade

fix action after upgrade

---

.github/workflows/ci-deb-packages-v2.yml

As per https://www.debian.org/doc/debian-policy/ch-controlfields.html#version we want to have only single `~` character in the version string and it must be the last splitter component of the entire version string.
Having multiple `~` in version string makes version comparison very unintuitive.
Consider this example:
```
0.1.0-999~buster-u1 > 0.1.0-7785001901~ef9e94e4f6~buster
0.1.0-999~buster-u1 < 0.1.0-7785001901-ef9e94e4f6~buster
0.1.0-999~buster < 0.1.0-7785001901~ef9e94e4f6~buster
0.1.0-999~buster < 0.1.0-7785001901-ef9e94e4f6~buster
```

Change DEB version format.

---

.github/workflows/ci-deb-packages-v2.yml

Add optional input configs:
-   DEB_BUILD_OPTIONS
-   INSTALL_DEPENDENCIES
-   VERSION_OVERRIDE
-   BOOTSTRAP_SCRIPT

Extend Debian build workflow with configuration options.

---

.github/workflows/ci-deb-packages-v2.yml

Reverts signalwire/actions-template#223
```
CPackDeb: Debian package release must confirm to "^[A-Za-z0-9.+~]+$" regex!
```

Revert "Change version delimiter for CMake."

---

.github/actions/meta-repo/action.yml

Remove `continue-on-error` from meto-repo action produced false-positive errors.

Remove `continue-on-error` from meto-repo action

---

.github/workflows/cd-swarm-deploy.yml

To reduce noise from large matrix deploys, allow individual deploys to skip slack notification.  Instead, a single slack notification will be sent for the collection of all services in the matrix.

Allow to skip slack message

---

.github/workflows/iac.yml

Rollback due to a bug introduced on v2
https://github.com/gruntwork-io/terragrunt-action/issues/67

Rollback Terragrunt Action

---

.github/actions/docker/action.yml
.github/workflows/ci-build.yml
.github/workflows/ci.yml

Useful to add port which will be app/image specific

Allow custom options on container test run

---

.github/actions/swarm-deploy/action.yml

Currently, the job is green even when the deploy fails. This causes confusion and extra work to debug.

Fail the job when deploy fails

---

.github/actions/test-ruby/action.yml
.github/workflows/ci-build.yml
.github/workflows/ci-check.yml
.github/workflows/ci.yml

use case is a Ruby app that also needs python setup.

Support additional setup in ruby pipelines

---

.github/actions/test-python/action.yml
.github/workflows/ci-check.yml
.github/workflows/ci.yml

initial minimal structure to allow python projects to build images (not actually running tests yet)

Add support for python builds

---

.github/actions/docker-build-artifacts/action.yml
.github/workflows/ci-deb-packages-v2.yml

PR adds waiter for docker daemon readiness and disables caching in `setup-qemu-action` to avoid warnings:
```
Post cache
Caching docker.io--tonistiigi--binfmt-latest-linux-x64 to GitHub Actions cache
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/mod_unimrcp/mod_unimrcp --files-from manifest.txt --use-compress-program zstdmt
Warning: Failed to save: Failed to CreateCacheEntry: Received non-retryable error: Failed request: (409) Conflict: cache entry with the same key, version, and scope already exists
```

Updates `docker-build-artifacts`, `ci-deb-packages-v2` workflows

---

.github/actions/docker-build-artifacts/action.yml

Add Docker daemon waiter with deadline of 60 seconds, should help with random fails that are happening on new `arm` runners.
Example of fail:
```
/usr/bin/docker version
Client: Docker Engine - Community
Version:           26.1.3
API version:       1.45
Go version:        go1.21.10
Git commit:        b72abbb
Built:             Thu May 16 08:40:13 2024
OS/Arch:           linux/arm64
Context:           default
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error: The process '/usr/bin/docker' failed with exit code 1
```

Add `Wait for Docker daemon` to `docker-build-artifacts`

---

.github/actions/update-gitops/action.yml

Get the variable into bash, then substitute. error 
```
signalwire/actions-template/main/.github/actions/update-gitops/action.yml (Line: 97, Col: 12): Unexpected symbol: 'IMAGE_TAG//:/-'. Located at position 8 within expression: inputs.IMAGE_TAG//:/-
```

fix: Separate GHA and bash substitution

---

.github/actions/update-gitops/action.yml

When triggered from another action (dispatch), there is no commit to reference
error is:
> fatal: empty ident name (for <>) not allowed

fix: add author when there is no commit

---

.github/actions/update-gitops/action.yml

To use the gh cli to create a PR, we need the token.
error
```
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
```

fix: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN

---

.github/actions/test-ruby/action.yml

appears new in [v6, merged last week](https://github.com/signalwire/actions-template/commit/a666f0dbb8d34fbab53d5e4b308d6f1634f2242c), causing too many PR CI failures

Disable rspec report comment

---

.github/actions/test-ruby/action.yml

Reverts signalwire/actions-template#344
ci is still failing after disabling comment, reverting to previous version

Revert "chore(deps): update sonicgarden/rspec-report-action action to v6"

---

.github/actions/update-gitops/action.yml
.github/workflows/cd-gitops.yml

Adds SWARM_SERVICE_NAME parameter to enable updating specific swarm services by service name rather than image name pattern. Maintains backward compatibility with existing SERVICE_NAME behavior.

Add targeted swarm service updates to GitOps workflow
